version: '3.7'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: coffee-db-local
    env_file:
      - .env.dev
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASS}"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${DB_PASS}\" -C -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: coffee-api-local
    env_file:
      - .env.dev
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy