services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    env_file:
      - .env.dev
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASS} 
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${DB_PASS}", "-Q", "IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'db_coffee') CREATE DATABASE db_coffee", "-C"]
      interval: 10s
      timeout: 5s
      retries: 10

  migration:
    build: .
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy 
    command: npm run migration:run

  api:
    build: .
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully 
    ports:
      - "3333:3333"