version: "3.7"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: desafioxlsx-db-1
    env_file:
      - ./coffee-backend-analysis/.env.dev
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    command: >
      bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 20;
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$DB_PASS\" -C
      -Q \"IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = '$$DB_NAME')
      CREATE DATABASE $$DB_NAME\";
      wait"
    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$DB_PASS\" -C -Q \"SELECT 1\" || exit 1"
      ]
      interval: 10s
      timeout: 10s
      retries: 10

  migration:
    build:
      context: ./coffee-backend-analysis
    container_name: desafioxlsx-migration-1
    env_file:
      - ./coffee-backend-analysis/.env.dev
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 5 && npm run migration:run"

  api:
    build:
      context: ./coffee-backend-analysis
    container_name: desafioxlsx-api-1
    env_file:
      - ./coffee-backend-analysis/.env.dev
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./coffee-frontend-analysis
    container_name: desafioxlsx-frontend-1
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://localhost:3333
    depends_on:
      - api
